{% set name = "Orange3-Fairness" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f76a3e47b9e7dce70e3f48db0eb0f25b74519abb5090d7330c0a6c2c7e49d050

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python <3.12
    - setuptools
  run:
    - aif360 ==0.5.0
    - numpy >=1.23.0,<1.24.dev0
    - orange3 >=3.32.0
    - python <3.12
    # scikit-learn is not directly a dependency, but the newer versions are currently having an issue with the scipy dependency.
    - scikit-learn =<1.3.2

test:
  imports:
    - orangecontrib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://orangedatamining.com/
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: "Orange3 add-on for fairness-aware machine learning."
  doc_url: https://orange3-fairness.readthedocs.io/en/latest/
  dev_url: https://github.com/biolab/orange3-fairness

extra:
  recipe-maintainers:
    - PrimozGodec
    - ZanMervic
    - HeavyTony2
    - markotoplak
