{% set name = "Orange3-Fairness" %}
{% set source_name = "orange3_fairness" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ source_name }}-{{ version }}.tar.gz
  sha256: 1e6aadcab198b9814ee99ddf024430e64fc5506c8eddd2744d84d63aa9b47af0

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - aif360 >=0.6.0
    - numpy
    - orange3 >=3.32.0
    - xgboost <2.1.1
    - serverfiles <0.3.0

test:
  imports:
    - orangecontrib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://orangedatamining.com/
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: "Orange3 add-on for fairness-aware machine learning."
  doc_url: https://orange3-fairness.readthedocs.io/en/latest/
  dev_url: https://github.com/biolab/orange3-fairness

extra:
  recipe-maintainers:
    - ZanMervic
    - PrimozGodec
    - HeavyTony2
    - markotoplak
